version: "3.8"

services:
  # following app and mysql is using same network specified by the Docker compose
  app:
    image: node:latest
    depends_on:
      mysql:
        condition: service_healthy
    command: sh -c "npm install && npx prisma generate && npx prisma migrate deploy
      && npx prisma db seed && npm run server"
    # map host port 8080 to container port 8080
    ports:
      - 8080:8080
    working_dir: /app
    # connet host path ./ to container path /app
    volumes:
      - ./:/app
    environment:
      # mysql will be resolve to service/mysql ip address
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: bold9

  # mysql is a service name and at the same time network alias
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: bold9
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 3s
      retries: 10
